---
title: "Welfare Expectations Across U.S. Economic Cycles"
subtitle: "Analysis of the the American public's views on government provision of benefits under different economic conditions over the past 50 years"
author: 
  - Tianen (Evan) Hao
thanks: "Code and data are available at: https://github.com/ShadyEvan4830/Welfare_Expectations_and_The_Economy.git. Links marked high-contrast 1:5 ratio green by Professor Alexander in lecture."
date: March 11, 2024
date-format: long
abstract: "A country's economic conditions often influence public opinion about government welfare actions. However, do all members of the public truly align with the general expectation of demanding higher welfare during economic downturns and less so when the economy is thriving? This study examines whether the American public believes government welfare initiatives have been adequate over the past 50 years, especially under varying economic circumstances. We meticulously analyze public sentiment on welfare provision during economic growth, stability, and recession periods, using data from the General Social Survey (GSS) 'Welfare.' Our analysis reveals that the public generally calls for reduced welfare spending during times of economic prosperity, while economic hardship triggers stronger demands for government assistance. Despite this trend, differences in welfare expectations among various demographic groups are evident. For instance, higher-income groups do not advocate for increased welfare support at any time, as this may impact their interests. This finding underscores the need for societies to tailor welfare policies to different groups, informing the development of fairer and more responsive welfare strategies amidst economic fluctuations."
format: pdf
toc: true
number-sections: true
bibliography: bibliography.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

#download the packages if necessary, then load the packages
if (!require("pacman")) install.packages("pacman")
pacman::p_load(janitor,here,dplyr,tidyverse,knitr,kableExtra,ggplot2)

library(janitor)
library(tidyverse)
library(knitr)
library(dplyr)
library(kableExtra)
library(here)
library(ggplot2)
```

# Introduction {#sec-intro}

Public attitudes towards government welfare programs fluctuate with economic conditions, swinging from calls for austerity during prosperous times to demands for increased support in downturns. This study investigates whether there's a consistent trend of advocating for reduced welfare spending in periods of economic prosperity, driven by beliefs in self-reliance and economic opportunity and whether there's a noticeable shift towards supporting more government welfare provisions during downturns, as seen during the 1982 recession, the 2008 Global Financial Crisis, and the 2020 COVID-19 pandemic. Importantly, we explore whether this trend is consistent across all public segments or if attitudes vary among different demographic groups.

Leveraging data from the General Social Survey (GSS) that spans decades, this paper examines the complex relationship between economic conditions and public sentiment towards welfare adequacy in the United States. We analyze public opinions during growth, stability, and recession periods to identify overall trends in welfare perceptions and their impact on demographics defined by income and employment status.

By comparing public welfare sentiments during economic downturns with those in stable economic periods, we aim to highlight the nuanced variations in public opinion on welfare provision. We hypothesize that the public expects more benefits during economic lows and fewer benefits during highs. Our preliminary findings reveal a multifaceted landscape of public opinion, with economic downturns significantly influencing the demand for increased government welfare action, albeit with notable variations across different demographic groups.

These findings have profound implications, indicating that a one-size-fits-all approach to welfare policy may not meet the diverse needs of the population effectively. Our research points to the benefits of developing welfare policies that are more responsive and tailored to the varied expectations and needs across the societal spectrum.

Structured to offer a comprehensive exploration of these themes, this paper begins with the current introduction that sets the stage for our investigation. The subsequent [Data] section outlines our methodology and data cleaning efforts, preparing the ground for our analysis. In the [Results] section, we present our findings on public welfare perceptions across varying economic conditions. The [Discussion] interprets these findings within the larger context of welfare policy and public expectations, leading to a contemplation of the study's limitations and potential directions for future research. We conclude with a synthesis of our key insights, emphasizing the critical need for nuanced and adaptable welfare policies. An [Appendix] provides further data and survey details, bolstering our analysis.


# Data {#sec-data}

This article analyzes data from the NORC General Social Survey (GSS) at the University of Chicago, specifically selecting the “welfare” data set from 1972 to 2024. The study enables a comparison of public perceptions of welfare adequacy in different economies. These include 1982, the 2008 global recession and the 2020 recession triggered by the COVID-19 pandemic.

## Source Data

This paper filters out selected variables from selected data variables in GSS and downloads them. The open source statistical programming language R [@citeR] and the libraries `tidyverse` [@tidyverse], `ggplot2` [@ggplot2], `dplyr` [@dplyr], `readr` [@readr clean data], are used in the data process. `tibble` [@tibble], `here` [@here], `kableExtra` [@kableExtra], `janitor` [@janitor] and `knitr` [@knitr].


## Data Cleaning

There are many unclear variable names in the original data set. In order to make the analysis clearer, we renamed the "natfare" variable name to "Response," because this variable mainly indicates the respondents' views on social welfare. Another variable used is "year". The purpose of this variable is to capture the year in which the survey was conducted. Finally, the variable contents of "ballot" and "x5" that are irrelevant to the paper were removed and at the same time, the position structure of the entire dataset was reorganized to better reflect the number of different responses each year..


## Survey Methodology

Between the years 1972 and 2018, the General Social Survey (GSS) primarily relied on in-person interviews for gathering data. The personal interaction inherent in these interviews allowed for a deeper exploration of responses, including the ability to address unclear answers more effectively. This traditional approach was considered highly effective for in-depth data gathering. However, due to the onset of the COVID-19 pandemic, the GSS adapted by shifting its data collection strategy to online surveys from 2020 through 2021.

The GSS focuses on engaging adults who are 18 years or older and communicate in English or Spanish, residing within the United States [@GSS]. This broad inclusion criterion enables a diverse group of participants to contribute to the survey. Yet, those who do not meet these language requirements or are unable to participate due to health reasons are excluded from the GSS's scope [@GSS].

Changes in how respondents were chosen for the GSS, including alterations to the Kish grid method, could potentially skew the representation of certain demographic groups. Moving to an online survey method might also lead to underrepresentation of older individuals, who may not be as digitally literate. This shift is significant as it could impact the understanding of labor trends among older adults, including stable employment and the challenges of age discrimination, which are vital for analyzing labor market trends comprehensively.

The focus of this review is on the survey methodologies employed during specific years: 1980, 1982, 2018, and 2021, correlating with the years of interest for the study of work hours. Participants were asked: "We are faced with many problems in this country, none of which can be solved easily or inexpensively. I'm going to name some of these problems, and for each one I'd like you to name some of these problems, and for each one I'd like you to tell me whether you think we're spending too much money on it, too little money, or about the right amount. First for welfare . . . are we spending too much, too little, or about the right amount on welfare?” The question's structure was consistently maintained from 1972 through 2022, ensuring the reliability of data collection and analysis over time. This consistency was crucial for achieving a thorough and consistent evaluation of the data, which included various modes of survey responses such as in-person, telephone, and web-based submissions.

## Statistical Analysis Methodology

Time-Series Analysis
In our study, we implemented time-series analysis as a core technique to trace the evolution of public opinions on welfare spending over an extended period. This method allowed us to meticulously map out and evaluate the trajectory of sentiments across decades, identifying any significant trends or sudden shifts in public perception. By analyzing the data as a series of time-ordered points, we were able to discern patterns such as cyclicality or trends corresponding to economic, political, or social events impacting public sentiment towards welfare policies.

Proportion Analysis
To further our understanding of the public's stance on welfare expenditure, we conducted a proportion analysis. This approach involved calculating the percentage of responses falling into predefined categories ('Too Much', 'Too Little', 'About Right') for each survey year. The proportion analysis facilitated a nuanced comparison across different periods, revealing how public sentiment towards welfare spending has fluctuated in response to changes in the socio-economic landscape. It also allowed us to gauge the intensity of public opinion and its alignment or divergence from policy shifts over time.

Ranking and Sorting
Ranking and sorting constituted another pivotal component of our statistical analysis. By categorizing years based on the extremity of sentiments expressed towards welfare spending, we pinpointed periods that stood out due to particularly pronounced public opinions. This method enabled us to isolate and scrutinize years with significant public consensus or discontent regarding welfare policies, offering insights into potential catalysts driving these sentiments and their implications on policy and societal norms.

## Visualization Approach
Line Graphs
For depicting the overarching trends in total survey responses over time, we utilized line graphs. This choice was instrumental in illustrating the engagement level with the subject of welfare spending, capturing fluctuations in public interest and participation in the discourse over the years. The continuous nature of line graphs facilitated a clear visualization of trends, highlighting periods of increased or decreased public engagement, and providing a temporal context for the analysis of sentiment shifts.

Bar Charts
Bar charts played a crucial role in our visualization strategy, especially in representing the proportion of 'Too Much' and 'Too Little' responses. By organizing data into discrete bars, we could effectively showcase the distribution of sentiments for each survey year. The use of color coding and horizontal orientation in certain visualizations was deliberately chosen to enhance the clarity and accessibility of the data, making it easier for readers to grasp the prevalence of specific opinions and their variations over time.

Comparative Visualizations
To draw comparisons between different years and spotlight shifts in public opinion relative to major economic and social events, we designed comparative visualizations. These visual tools were essential in juxtaposing data points from various periods, underscoring the impact of external factors on public sentiment towards welfare spending. Through these visual comparisons, we aimed to provide a more dynamic and contextualized interpretation of the data, enabling readers to connect fluctuations in public opinion with broader socio-economic developments.

# Model Approach

The goal of our modelling strategy is twofold. Firstly,...

Here we briefly describe the linear analysis model used to investigate... Background details and diagnostics are included in [Appendix -@sec-model-details].

## Model Set-up

Will update later.

### Model Justification

Will update later.

# Data Limitations

Will update later.

# Results

Will update later.


# Discussion

Will update later.

## First discussion point {#sec-first-point}

## Second discussion point

## Third discussion point

## Weaknesses and next steps

Weaknesses and next steps should also be included.

\newpage

\appendix

# Appendix {-}


# Additional data details

# Model details {#sec-model-details}

## Posterior predictive check


\newpage


# References


